In [1]:
import os
import json
import pandas as pd
import mysql.connector as sql

In [2]:
# aggregated folder details to be fetched and converted to data frame
# aggregator_transaction

path1 = "E:/GUVI Projects/Phonepe Pulse/pulse/data/aggregated/transaction/country/india/state/"
aggr_tran_list = os.listdir(path1)


columns1 = {"States":[], "Years":[], "Quarter":[], "Transaction_type":[], "Transaction_count":[], "Transaction_amount":[]}
for state in aggr_tran_list:
    current_states = path1+state+"/" # the end / is to select the folders within the state folder
    aggr_year_list = os.listdir(current_states)
    
    for year in aggr_year_list:
        current_year = current_states +year+"/"
        aggr_file_list = os.listdir(current_year)   # creating the loop to load the csv files.
                                                  # one by one loading is difficult so creating a loop for uploading
        for file in aggr_file_list:
            current_file = current_year + file
            data = open(current_file, "r")

            A = json.load(data)
            for i in A["data"]["transactionData"]:
                name = i['name']
                count = i["paymentInstruments"][0]["count"]
                amt = i["paymentInstruments"][0]["amount"]
                columns1["Transaction_type"].append(name)
                columns1["Transaction_count"].append(count)
                columns1["Transaction_amount"].append(amt)
                columns1["States"].append(state)
                columns1["Years"].append(year)
                columns1["Quarter"].append(int(file.strip(".json")))

In [3]:
aggre_transaction = pd.DataFrame(columns1) # converting it to df so that neatly represented in tables.

aggre_transaction

,States,Years,Quarter,Transaction_type,Transaction_count,Transaction_amount
0,andaman-&-nicobar-islands,2018,1,Recharge & bill payments,4200,1.845307e+06
1,andaman-&-nicobar-islands,2018,1,Peer-to-peer payments,1871,1.213866e+07
2,andaman-&-nicobar-islands,2018,1,Merchant payments,298,4.525072e+05
3,andaman-&-nicobar-islands,2018,1,Financial Services,33,1.060142e+04
4,andaman-&-nicobar-islands,2018,1,Others,256,1.846899e+05
...,...,...,...,...,...,...
4129,west-bengal,2023,3,Merchant payments,296965002,2.004404e+11
4130,west-bengal,2023,3,Peer-to-peer payments,271150280,8.310501e+11
4131,west-bengal,2023,3,Recharge & bill payments,63055684,3.920985e+10
4132,west-bengal,2023,3,Financial Services,389751,4.249856e+08
4133,west-bengal,2023,3,Others,532474,4.232851e+08

In [4]:
# aggregator_user
path2 = "E:/GUVI Projects/Phonepe Pulse/pulse/data/aggregated/user/country/india/state/"
aggr_user_list = os.listdir(path2)


columns2 = {"States":[], "Years":[], "Quarter":[], "Brands":[], "Transaction_count":[], "Percentage":[]}
for state in aggr_user_list:
    current_states = path2+state+"/" # the end / is to select the folders within the state folder
    aggr_year_list = os.listdir(current_states)
    
    for year in aggr_year_list:
        current_year = current_states +year+"/"
        aggr_file_list = os.listdir(current_year)   # creating the loop to load the csv files.
                                                  # one by one loading is difficult so creating a loop for uploading
        for file in aggr_file_list:
            current_file = current_year + file
            data = open(current_file, "r")

            B = json.load(data)
            
            try:
                for i in B["data"]["usersByDevice"]:
                    brand = i["brand"]
                    count = i["count"]
                    percentage = i["percentage"]
                    columns2["Brands"].append(brand)
                    columns2["Transaction_count"].append(count)
                    columns2["Percentage"].append(percentage)
                    columns2["States"].append(state)
                    columns2["Years"].append(year)
                    columns2["Quarter"].append(int(file.strip(".json")))
            
            except:
                pass

In [5]:
aggre_user = pd.DataFrame(columns2) # converting it to df so that neatly represented in tables.

In [6]:
#map folder details to be fetched

path3 = "E:/GUVI Projects/Phonepe Pulse/pulse/data/map/transaction/hover/country/india/state/"
map_tran_list = os.listdir(path3)

columns3 = {"States":[], "Years":[], "Quarter":[], "District_name":[], "Transaction_count":[], "Amount":[]}
for state in map_tran_list:
    current_states = path3+state+"/" # the end / is to select the folders within the state folder
    aggr_year_list = os.listdir(current_states)
    
    for year in aggr_year_list:
        current_year = current_states +year+"/"
        aggr_file_list = os.listdir(current_year)   # creating the loop to load the csv files.
                                                  # one by one loading is difficult so creating a loop for uploading
        for file in aggr_file_list:
            current_file = current_year + file
            data = open(current_file, "r")

            C = json.load(data)
            
            for i in C["data"]["hoverDataList"]:
                dist_name = i["name"]
                count = i["metric"][0]["count"]
                amt = i["metric"][0]["amount"]
                columns3["District_name"].append(dist_name)
                columns3["Transaction_count"].append(count)
                columns3["Amount"].append(amt)
                columns3["States"].append(state)
                columns3["Years"].append(year)
                columns3["Quarter"].append(int(file.strip(".json")))

In [7]:
map_tran = pd.DataFrame(columns3)

In [8]:
path4 = "E:/GUVI Projects/Phonepe Pulse/pulse/data/map/user/hover/country/india/state/"
map_user_list = os.listdir(path4)

columns4 = {"States":[], "Years":[], "Quarter":[], "District_name":[], "Registered_users":[], "App_opens":[]}
for state in map_user_list:
    current_states = path4+state+"/" # the end / is to select the folders within the state folder
    aggr_year_list = os.listdir(current_states)
    
    for year in aggr_year_list:
        current_year = current_states +year+"/"
        aggr_file_list = os.listdir(current_year)   # creating the loop to load the csv files.
                                                  # one by one loading is difficult so creating a loop for uploading
        for file in aggr_file_list:
            current_file = current_year + file
            data = open(current_file, "r")

            D = json.load(data)
            

            for i in D["data"]["hoverData"].items():
                dist_name = i[0]
                regd_users = i[1]["registeredUsers"]
                app_opens = i[1]["appOpens"]
                columns4["District_name"].append(dist_name)
                columns4["Registered_users"].append(regd_users)
                columns4["App_opens"].append(app_opens)
                columns4["States"].append(state)
                columns4["Years"].append(year)
                columns4["Quarter"].append(int(file.strip(".json")))

In [9]:
map_user = pd.DataFrame(columns4)

In [10]:
#Top data fetched and converted into data frames

path5 = "E:/GUVI Projects/Phonepe Pulse/pulse/data/top/transaction/country/india/state/"
top_tran_list = os.listdir(path5)

columns5 = {"States":[], "Years":[], "Quarter":[], "Pincodes":[], "Transaction_count":[], "Transaction_amount":[]}
for state in top_tran_list:
    current_states = path5+state+"/" # the end / is to select the folders within the state folder
    aggr_year_list = os.listdir(current_states)
    
    for year in aggr_year_list:
        current_year = current_states +year+"/"
        aggr_file_list = os.listdir(current_year)   # creating the loop to load the csv files.
                                                  # one by one loading is difficult so creating a loop for uploading
        for file in aggr_file_list:
            current_file = current_year + file
            data = open(current_file, "r")

            E = json.load(data)

            for i in E["data"]["pincodes"]:
                entityName = i["entityName"]
                count = i["metric"]["count"]
                amount = i["metric"]["amount"]
                columns5["Pincodes"].append(entityName)
                columns5["Transaction_count"].append(count)
                columns5["Transaction_amount"].append(amount)
                columns5["States"].append(state)
                columns5["Years"].append(year)
                columns5["Quarter"].append(int(file.strip(".json")))

In [11]:
top_tran = pd.DataFrame(columns5)

In [12]:
path6 = "E:/GUVI Projects/Phonepe Pulse/pulse/data/top/user/country/india/state/"
top_user_list = os.listdir(path6)

columns6 = {"States":[], "Years":[], "Quarter":[], "Pincodes":[], "Registered_User":[]}
for state in top_user_list:
    current_states = path6+state+"/" # the end / is to select the folders within the state folder
    aggr_year_list = os.listdir(current_states)
    
    for year in aggr_year_list:
        current_year = current_states +year+"/"
        aggr_file_list = os.listdir(current_year)   # creating the loop to load the csv files.
                                                  # one by one loading is difficult so creating a loop for uploading
        for file in aggr_file_list:
            current_file = current_year + file
            data = open(current_file, "r")

            F = json.load(data)
            
            for i in F["data"]["pincodes"]:
                name = i["name"]
                registered_users = i["registeredUsers"]
                columns6["Pincodes"].append(name)
                columns6["Registered_User"].append(registered_users)
                columns6["States"].append(state)
                columns6["Years"].append(year)
                columns6["Quarter"].append(int(file.strip(".json")))

In [13]:
top_user = pd.DataFrame(columns6)

In [14]:
mydb = sql.connect(host="localhost",
                   user="root",
                   password="Rohan@sql04",
                   database= "Phonepe_db",
                   use_pure = True
                  )
mycursor = mydb.cursor()

create_query1 = """CREATE TABLE if not exists aggregated_transaction (States varchar(50),
                                                                      Years int,
                                                                      Quarter int,
                                                                      Transaction_type varchar(50),
                                                                      Transaction_count bigint,
                                                                      Transaction_amount bigint)"""
mycursor.execute(create_query1)
mydb.commit()

for index,row in aggre_transaction.iterrows():
    insert_query1 = '''INSERT INTO aggregated_transaction (States, Years, Quarter, Transaction_type, Transaction_count, Transaction_amount)
                                                        values(%s,%s,%s,%s,%s,%s)'''
    values = (row["States"],
              row["Years"],
              row["Quarter"],
              row["Transaction_type"],
              row["Transaction_count"],
              row["Transaction_amount"]
              )
    mycursor.execute(insert_query1,values)
    mydb.commit()

In [15]:
#aggregated user table
create_query2 = '''CREATE TABLE if not exists aggregated_user (States varchar(50),
                                                                Years int,
                                                                Quarter int,
                                                                Brands varchar(50),
                                                                Transaction_count bigint,
                                                                Percentage float)'''
mycursor.execute(create_query2)
mydb.commit()

for index,row in aggre_user.iterrows():
    insert_query2 = '''INSERT INTO aggregated_user (States, Years, Quarter, Brands, Transaction_count, Percentage)
                                                    values(%s,%s,%s,%s,%s,%s)'''
    values = (row["States"],
              row["Years"],
              row["Quarter"],
              row["Brands"],
              row["Transaction_count"],
              row["Percentage"])
    mycursor.execute(insert_query2,values)
    mydb.commit()

In [16]:
#map_transaction_table
create_query3 = '''CREATE TABLE if not exists map_transaction (States varchar(50),
                                                                Years int,
                                                                Quarter int,
                                                                District varchar(50),
                                                                Transaction_count bigint,
                                                                Transaction_amount float)'''
mycursor.execute(create_query3)
mydb.commit()

for index,row in map_tran.iterrows():
            insert_query3 = '''
                INSERT INTO map_Transaction (States, Years, Quarter, District, Transaction_count, Transaction_amount)
                VALUES (%s, %s, %s, %s, %s, %s)

            '''
            values = (
                row['States'],
                row['Years'],
                row['Quarter'],
                row['District_name'],
                row['Transaction_count'],
                row['Amount']
            )
            mycursor.execute(insert_query3,values)
            mydb.commit() 

#map_user_table
create_query4 = '''CREATE TABLE if not exists map_user (States varchar(50),
                                                        Years int,
                                                        Quarter int,
                                                        Districts varchar(50),
                                                        RegisteredUser bigint,
                                                        AppOpens bigint)'''
mycursor.execute(create_query4)
mydb.commit()

for index,row in map_user.iterrows():
    insert_query4 = '''INSERT INTO map_user (States, Years, Quarter, Districts, RegisteredUser, AppOpens)
                        values(%s,%s,%s,%s,%s,%s)'''
    values = (row["States"],
              row["Years"],
              row["Quarter"],
              row["District_name"],
              row["Registered_users"],
              row["App_opens"])
    mycursor.execute(insert_query4,values)
    mydb.commit()

#top_transaction_table
create_query5 = '''CREATE TABLE if not exists top_transaction (States varchar(50),
                                                                Years int,
                                                                Quarter int,
                                                                pincodes int,
                                                                Transaction_count bigint,
                                                                Transaction_amount bigint)'''
mycursor.execute(create_query5)
mydb.commit()

for index,row in top_tran.iterrows():
    insert_query5 = '''INSERT INTO top_transaction (States, Years, Quarter, Pincodes, Transaction_count, Transaction_amount)
                                                    values(%s,%s,%s,%s,%s,%s)'''
    values = (row["States"],
              row["Years"],
              row["Quarter"],
              row["Pincodes"],
              row["Transaction_count"],
              row["Transaction_amount"])
    mycursor.execute(insert_query5,values)
    mydb.commit()

#top_user_table
create_query6 = '''CREATE TABLE if not exists top_user (States varchar(50),
                                                        Years int,
                                                        Quarter int,
                                                        Pincodes int,
                                                        RegisteredUser bigint
                                                        )'''
mycursor.execute(create_query6)
mydb.commit()

for index,row in top_user.iterrows():
    insert_query6 = '''INSERT INTO top_user (States, Years, Quarter, Pincodes, RegisteredUser)
                                            values(%s,%s,%s,%s,%s)'''
    values = (row["States"],
              row["Years"],
              row["Quarter"],
              row["Pincodes"],
              row["Registered_User"])
    mycursor.execute(insert_query6,values)
    mydb.commit()